version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"